@startuml
entity Pet {
  id
  breed_id // порода
  name
  age
  color
}

entity Pet_Person {
  pet_id
  person_id
  ownership_start_date
  ownership_end_date
}

entity Person {
  id
  name
}

entity Breed {
  id
  name
}

entity Animal_Type {
  id
  name
}

entity Insurance_Package {
  // страховой пакет
  id
  name
  base_cost
  create_date
  death_date
}

entity Service {
  id
  name
  deprecated
}

entity Insurance_Package_Service {
  insurance_package_id
  service_id
}

entity Insurance {
  id
  person_id
  insurance_package_id
  date_start
  date_end
}

entity Insurance_Pet {
  insurence_id
  pet_id
}

Person -right-+ Pet_Person
Pet_Person +-right- Pet
Breed -left-+ Pet
Animal_Type --+ Breed

Insurance_Package -right-+ Insurance_Package_Service
Insurance_Package_Service +-right- Service

Person --+ Insurance
Insurance +-- Insurance_Package

Pet --+ Insurance_Pet
Insurance_Pet +-left- Insurance

@enduml