@startuml
entity Pet {
  id
  id_breed // порода
  name
  color
  sex
  birth_date
  death_date
}

entity Pet_Person {
  id
  id_pet
  id_person
  ownership_start_date
  ownership_end_date
}

entity Person {
  id
  first_name
  surname
  last_name
  login
  password
}

entity Breed {
  id
  name
  id_animal_type
}

entity Animal_Type {
  id
  name
}

entity Insurance_Package {
  // страховой пакет
  id
  name
  base_cost
  create_date
  death_date
}

entity Service {
  id
  name
  deprecated
}

entity Insurance_Package_Service {
  id_insurance_package
  id_service
}

entity Insurance {
  id
  id_pet_person
  id_insurance_package
  date_start
  date_end
}

Person -right-+ Pet_Person
Pet_Person +-right- Pet
Breed -left-+ Pet
Animal_Type --+ Breed

Insurance_Package -right-+ Insurance_Package_Service
Insurance_Package_Service +-right- Service

Pet_Person --+ Insurance
Insurance +-- Insurance_Package

@enduml